# Provisioning the environments with necessary app files

---

- name: Synchronising instance
  hosts: live_env
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo

  tasks:
  - name: Sync App_Files
    synchronize:
      src: /home/ubuntu/App_Files
      dest: /home/ubuntu/
    become: true

  - name: Install python dependencies
    apt:
      name:
        - python3
        - python-pip
        - python3-pip
      state: present
      update_cache: true
    become: true

  - name: Install all dependencies from requirements.txt
    shell: python3 -m pip install -r App_Files/requirements.txt
    become: true

  - name: Creates a Downloads folder so the app puts the csv there
    file:
      path: ~/Downloads
      state: directory

  - name: Start the app and download the csv file into the downloads folder
    shell: |
      cd App_Files
      python3 main.py
      1
      2
    become: true

    # sudo ansible-playbook --ask-vault-pass playbook_provision.yaml -u ubuntu

#    scp -o "StrictHostKeyChecking=no" -i $AWS_ACCESS -r App_Files/ ubuntu@34.244.153.28:~/
#    ssh -o "StrictHostKeyChecking=no" -i $AWS_ACCESS ubuntu@34.244.153.28<<EOF
#    sudo apt update
#    sudo apt install python3 -y
#    sudo apt install python3-pip -y
#    python3 -m pip install -r App_Files/requirements.txt
#    EOF